name: Handle Secret Scanning Alerts
on:
  repository_dispatch:
    types: [secret_scanning_alert]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Alert
        uses: slackapi/slack-github-action@v1
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL }}
          message: "Se ha detectado un secreto en el repositorio. Revisar alerta de Secret Scanning."
