name: Notificar a Slack cuando se hace push a develop

on:
  push:
    branches:
      - develop

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Notificar a Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          APP_NAME: ${{ secrets.APP_NAME }}
          PUSHER_NAME: ${{ github.event.pusher.name }}
          PUSHER_EMAIL: ${{ github.event.pusher.email }}
          COMMIT_MSG: ${{ github.event.head_commit.message }}
        run: |
          curl --fail -X POST -H 'Content-type: application/json' --data "{
            \"text\": \"🚀 *Push detectado en develop* para *${APP_NAME}*.\n👤 Usuario: *${PUSHER_NAME}* (${PUSHER_EMAIL})\n📝 Commit: ${COMMIT_MSG}\"
          }" $SLACK_WEBHOOK_URL
